name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
jobs:
  tsc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: yarn install --pure-lockfile
      - run: yarn tsc
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: yarn install --pure-lockfile
      - run: yarn lint
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: yarn install --pure-lockfile
      - run: yarn test
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: yarn install --pure-lockfile
      - run: yarn build
