name: release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # semantic-releaseがrepositoryへのpush権限を要求する
      issues: read    # semantic-releaseがissueを検索できるように
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - run: yarn install --pure-lockfile
      - run: yarn build
      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
